// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzdfyikvgkolunfmghdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6ZGZ5aWt2Z2tvbHVuZm1naGRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDYxMzcsImV4cCI6MjA3MDAyMjEzN30.MTyjuU9SOfe5Jg268niVFGfMws122trcrJ_f7Wmw_6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});